### PR TITLE
Chore: Add LICENSE file to created package

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Added `LICENSE` file to created package if is available.

## Additional info
Created package has no information about it's licensing. A person has to go to a corresponding repository, but usually information about repository is not available in the package.

## Testing notes:
1. Validate if it makes sense to add license to package.

### CODE REVIEW

**Review by kalisp — DISMISSED** [review]
It makes sense to me to incorporate license in client code.

**Comment by iLLiCiTiT** [comment]
> It makes sense to me to incorporate license in client code.

This actually adds license only to server addon. Should we add it to client code too?

**Comment by kalisp** [comment]
Ohh, I would think so.

**Comment by iLLiCiTiT** [comment]
Added LICENSE to client code too

**Pull request merged**
